name: Continuous Integration Workflow
on:
  workflow_dispatch: # Manually trigger a workflow https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  pull_request: # Pull Requests
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "OK"
          echo "DEBUG"
          exit 1
      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
